
version: '3.8'
services:
  web:
    build: ./web_server
    ports:
      - "80:80"
  sql_server:
    build: ./sql_server
    environment:
      SA_PASSWORD: YourStrong!Passw0rd
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
